### ISSUE TITLE
Run GroovyModuleLoaderExample in IDEA , Win7 Path error

### ISSUE THREAD

**Issue by ahypnos** [Netflix/Nicobar#40]
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/ahypnos/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.3.6/dfe5f424777f4579786ec2145fc43286fcda8195/groovy-all-2.3.6.jar
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.netflix.nicobar.core.utils.ClassPathUtils.getJarPathFromUrl(ClassPathUtils.java:114)
	at com.netflix.nicobar.core.utils.ClassPathUtils.findRootPathForResource(ClassPathUtils.java:73)
	at com.netflix.nicobar.example.groovy2.ExampleResourceLocator.getGroovyRuntime(ExampleResourceLocator.java:50)
	at com.netflix.nicobar.example.groovy2.GroovyModuleLoaderExample.runExample(GroovyModuleLoaderExample.java:73)
	at com.netflix.nicobar.example.groovy2.GroovyModuleLoaderExample.main(GroovyModuleLoaderExample.java:67)

**Comment by hastebrot** [comment]
I get the same exception. This is due to the `:` after the drive letter.

**Comment by hastebrot** [comment]
We need to replace `/C:/...` with `C:/...`.

~~~java
import java.nio.file.Path;
import java.nio.file.Paths;

import org.apache.commons.io.FileUtils;

public class WindowsPathIssue {
    public static void main(String[] args) {
        Path pathToNotepad = Paths.get("/C:/Windows/notepad.exe");
        System.out.println(FileUtils.sizeOf(pathToNotepad.toFile()));
    }
}
~~~

**Comment by hastebrot** [comment]
Here is a test case for `ClassPathUtilsTest`. Note that both assertions fail on a Windows machine, because the first call to `getJarPathFromUrl()` returns a path with `\` as path separator.

~~~java
@Test
public void testGetJarPathFromUrl() throws Exception {
    URL posixPath = new URL("jar:file:/path/to/groovy.jar!/path/to/resource.txt");
    URL windowsPath = new URL("jar:file:/C:/path/to/groovy.jar!/path/to/resource.txt");
    assertEquals(ClassPathUtils.getJarPathFromUrl(posixPath).toString(), "/path/to/groovy.jar");
    assertEquals(ClassPathUtils.getJarPathFromUrl(windowsPath).toString(), "C:/path/to/groovy.jar");
}
~~~

**Comment by hastebrot** [comment]
Hmm, seems that we can't influence how `Paths.get()` handles path separators under Windows. :cry:

~~~java
System.out.println(Paths.get("/foo/bar")); // outputs "\foo\bar".
~~~

**Comment by hastebrot** [comment]
This code should solve the issue:

~~~java
@Test
public void testGetJarPathFromUrl() throws Exception {
    // Regression tests for https://github.com/Netflix/Nicobar/issues/40.
    URL pathOnPosix = new URL("jar:file:/path/to/groovy.jar!/path/to/resource.txt");
    URL pathOnWindows = new URL("jar:file:/C:/path/to/groovy.jar!/path/to/resource.txt");
    URL pathWithSpaces = new URL("jar:file:/D:/path to/groovy.jar!/path to/resource.txt");
    assertEquals("/path/to/groovy.jar",
        ClassPathUtils.getJarPathFromUrl(pathOnPosix).toString().replace("\\", "/"));
    assertEquals("C:/path/to/groovy.jar",
        ClassPathUtils.getJarPathFromUrl(pathOnWindows).toString().replace("\\", "/"));
    assertEquals("D:/path to/groovy.jar",
        ClassPathUtils.getJarPathFromUrl(pathWithSpaces).toString().replace("\\", "/"));
}
~~~

Version 1:

~~~java
public static Path getJarPathFromUrl(URL jarUrl) {
    String jarPath = jarUrl.getPath();
    int startIndex = jarPath.startsWith("file:") ? 5 : 0;
    int endIndex = jarPath.lastIndexOf("!");
    String jarFilePath = jarPath.substring(startIndex, endIndex);
    return Paths.get(new File(jarFilePath).getPath());
}
~~~

Version 2:

~~~java
public static Path getJarPathFromUrl(URL jarUrl) {
    try {
        JarURLConnection connection = (JarURLConnection) jarUrl.openConnection();
        URL jarFileUrl = connection.getJarFileURL();
        String jarFilePath = new File(jarFileUrl.toURI()).getPath();
        return Paths.get(jarFilePath);
    }
    catch (Exception exception) {
        throw new RuntimeException(exception);
    }
}
~~~

**Comment by hastebrot** [comment]
There is another exception with `ArchiveRepositoryPoller` and `Paths.get()`. The poller wants `Paths` to handle Windows paths with `:` in the file name:

~~~
java.nio.file.InvalidPathException: Illegal char <:> at index 10: HelloWorld:1428014423748
~~~

**Comment by hastebrot** [comment]
The class `org.jboss.modules.ModuleIdentifier` contains following method, which used by `JBossModuleUtils.createRevisionId()` and generated the revision id, i.e. `HelloWorld:1428014423748`.

~~~java
public String toString() {
    return name + ":" + slot;
}
~~~

**Comment by hastebrot** [comment]
My suggestion is, to add a wrapper method for `Paths.get()` into `ClassPathUtils` and substitute all calls to `Paths.get()` with the wrapper method:

~~~java
public static Path getPath(String pathString) {
    File pathFile = new File(pathString);
    return Paths.get(pathFile.getParent(), pathFile.getName().replace(":", "_"));
}
~~~

**Comment by whisperwing** [comment]
@hastebrot did you run into problem with the example if you update jar file at runtime?

**Comment by hastebrot** [comment]
@whisperwing  I haven't tested this, yet.

**Comment by whisperwing** [comment]
@hastebrot I found that replacing jar file without name change wouldn't work. Likely because of https://github.com/Netflix/Nicobar/issues/37
