### ISSUE TITLE
Error java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.closeQuietly(Ljava/io/Closeable;)

### ISSUE THREAD

**Issue by zhangfeiyu2005** [Netflix/Nicobar#48]
Hello,

I so excited your lib, but when i tried with latest lib from __JDKPaths class like:
nicobar-core-0.3.0.jar
IOUtils.closeQuietly(ZipFile) method not exist
run it will show error like:

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.closeQuietly(Ljava/io/Closeable;)V
	at com.netflix.nicobar.core.utils.__JDKPaths.processJar(__JDKPaths.java:96)
	at com.netflix.nicobar.core.utils.__JDKPaths.processClassPathItem(__JDKPaths.java:73)
	at com.netflix.nicobar.core.utils.__JDKPaths.<clinit>(__JDKPaths.java:54)
	at com.netflix.nicobar.core.utils.ClassPathUtils.getJdkPaths(ClassPathUtils.java:51)
	at com.netflix.nicobar.core.module.jboss.JBossModuleUtils.<clinit>(JBossModuleUtils.java:78)
	at com.netflix.nicobar.core.module.ScriptModuleLoader.addCompilerPlugin(ScriptModuleLoader.java:394)
	at com.netflix.nicobar.core.module.ScriptModuleLoader.<init>(ScriptModuleLoader.java:172)
	at com.netflix.nicobar.core.module.ScriptModuleLoader$Builder.build(ScriptModuleLoader.java:144)
	at main.java.com.netflix.nicobar.example.groovy2.GroovyModuleLoaderExample.runExample(GroovyModuleLoaderExample.java:71)
	at main.java.com.netflix.nicobar.example.groovy2.GroovyModuleLoaderExample.main(GroovyModuleLoaderExample.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

I used your nicobar-example

Cheers,
feiyu.zhang

**Comment by balakrishna-gajam** [comment]
Its due to version conflicts.
